import type { CarListing, PropertyListing, ServiceProvider } from '../types';

export const sampleCars: CarListing[] = [
  {
    id: 'car-1',
    title: 'تويوتا كامري 2024 فل كامل',
    price: 48000000,
    location: 'بغداد - المنصور',
    km: '12,000',
    fuel: 'بنزين',
    year: '2024',
    condition: 'جديد',
    make: 'تويوتا',
    model: 'كامري',
    color: 'أبيض لؤلؤي',
    description: 'تويوتا كامري 2024 فل كامل مواصفات خليجية، فتحة سقف بانوراما، كاميرا 360 درجة، شاشة لمس، جلد طبيعي، نظام ملاحة، بلوتوث.',
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=400',
    images: [],
    sellerName: 'معرض النجم للسيارات',
    sellerPhone: '07701234567',
    promoted: true,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    userId: 'system',
  },
  {
    id: 'car-2',
    title: 'هيونداي إلنترا 2023 ستاندرد',
    price: 32000000,
    location: 'أربيل - عينكاوا',
    km: '25,000',
    fuel: 'بنزين',
    year: '2023',
    condition: 'مستعمل',
    make: 'هيونداي',
    model: 'إلنترا',
    color: 'رمادي',
    description: 'هيونداي إلنترا 2023 بحالة ممتازة، صيانة دورية عند الوكيل، إطارات جديدة، بدون حوادث.',
    image: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=400',
    images: [],
    sellerName: 'كريم أحمد',
    sellerPhone: '07809876543',
    promoted: false,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    userId: 'system',
  },
  {
    id: 'car-3',
    title: 'كيا سبورتاج 2024 GT Line',
    price: 55000000,
    location: 'بغداد - الكرادة',
    km: '5,000',
    fuel: 'بنزين',
    year: '2024',
    condition: 'جديد',
    make: 'كيا',
    model: 'سبورتاج',
    color: 'أسود',
    description: 'كيا سبورتاج GT Line 2024 جديد، شاشة كبيرة، مقاعد جلد كهربائية، نظام دفع رباعي، كاميرا خلفية.',
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=400',
    images: [],
    sellerName: 'معرض الخليج للسيارات',
    sellerPhone: '07711234567',
    promoted: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    userId: 'system',
  },
  {
    id: 'car-4',
    title: 'نيسان صني 2022',
    price: 22000000,
    location: 'البصرة - الزبير',
    km: '40,000',
    fuel: 'بنزين',
    year: '2022',
    condition: 'مستعمل',
    make: 'نيسان',
    model: 'صني',
    color: 'فضي',
    description: 'نيسان صني 2022 اقتصادية، استهلاك وقود ممتاز، مناسبة للعائلة، جير أوتوماتيك.',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400',
    images: [],
    sellerName: 'علي محمد',
    sellerPhone: '07801234567',
    promoted: false,
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    userId: 'system',
  },
  {
    id: 'car-5',
    title: 'BMW X5 2023 M Sport',
    price: 85000000,
    location: 'بغداد - زيونة',
    km: '15,000',
    fuel: 'بنزين',
    year: '2023',
    condition: 'مستعمل',
    make: 'BMW',
    model: 'X5',
    color: 'أزرق ميتاليك',
    description: 'BMW X5 M Sport 2023، محرك 3.0 توربو، مواصفات أوروبية كاملة، فتحة سقف، نظام صوتي Harman Kardon.',
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400',
    images: [],
    sellerName: 'معرض الفخامة',
    sellerPhone: '07901234567',
    promoted: false,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    userId: 'system',
  },
  {
    id: 'car-6',
    title: 'مرسيدس C200 2024 AMG',
    price: 92000000,
    location: 'أربيل - 100 متر',
    km: '3,000',
    fuel: 'بنزين',
    year: '2024',
    condition: 'جديد',
    make: 'مرسيدس',
    model: 'C200',
    color: 'أبيض',
    description: 'مرسيدس C200 AMG 2024 جديد بالكرتون، مواصفات خليجية كاملة، ضمان الوكيل، حساسات أمامية وخلفية.',
    image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=400',
    images: [],
    sellerName: 'وكالة النجمة الذهبية',
    sellerPhone: '07501234567',
    promoted: true,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    userId: 'system',
  },
];

export const sampleProperties: PropertyListing[] = [
  {
    id: 'prop-1',
    title: 'شقة فاخرة في المنصور 180م',
    price: 250000000,
    type: 'شقة',
    purpose: 'بيع',
    area: '180',
    beds: 3,
    baths: 2,
    location: 'بغداد - المنصور',
    description: 'شقة فاخرة بتشطيبات سوبر ديلوكس في حي المنصور، طابق 5 مع مصعد، 3 غرف نوم وصالة كبيرة، مطبخ مجهز، تكييف مركزي، موقف سيارة خاص.',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400',
    images: [],
    ownerName: 'مكتب دار العقار',
    ownerPhone: '07701234568',
    promoted: true,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    userId: 'system',
    furnished: false,
  },
  {
    id: 'prop-2',
    title: 'بيت مستقل في زيونة 300م',
    price: 450000000,
    type: 'بيت',
    purpose: 'بيع',
    area: '300',
    beds: 5,
    baths: 3,
    location: 'بغداد - زيونة',
    description: 'بيت مستقل بمساحة 300م مربع على أرض 200م، 5 غرف نوم، 3 حمامات، حديقة أمامية وخلفية، كراج سيارتين، بناء 2020.',
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400',
    images: [],
    ownerName: 'حسن عبدالله',
    ownerPhone: '07801234568',
    promoted: false,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    userId: 'system',
    furnished: false,
  },
  {
    id: 'prop-3',
    title: 'مكتب تجاري في الكرادة',
    price: 1500000,
    type: 'مكتب',
    purpose: 'إيجار',
    area: '120',
    beds: 0,
    baths: 1,
    location: 'بغداد - الكرادة',
    description: 'مكتب تجاري جاهز في شارع الكرادة الرئيسي، مناسب لمكاتب المحاماة والشركات، تكييف مركزي، إنترنت، حارس أمن.',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400',
    images: [],
    ownerName: 'مكتب الأمانة العقاري',
    ownerPhone: '07711234568',
    promoted: true,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    userId: 'system',
    furnished: true,
  },
  {
    id: 'prop-4',
    title: 'أرض سكنية في أربيل 200م',
    price: 180000000,
    type: 'أرض',
    purpose: 'بيع',
    area: '200',
    beds: 0,
    baths: 0,
    location: 'أربيل - عينكاوا',
    description: 'أرض سكنية بموقع مميز في عينكاوا، واجهة 10م، عمق 20م، شارع 12م، قريبة من المدارس والمراكز التجارية.',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400',
    images: [],
    ownerName: 'ديار للعقارات',
    ownerPhone: '07501234568',
    promoted: false,
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    userId: 'system',
    furnished: false,
  },
  {
    id: 'prop-5',
    title: 'شقة مفروشة للإيجار اليومي',
    price: 85000,
    type: 'شقة',
    purpose: 'إيجار يومي',
    area: '100',
    beds: 2,
    baths: 1,
    location: 'البصرة - العشار',
    description: 'شقة مفروشة فرش فاخر للإيجار اليومي في البصرة، غرفتين نوم وصالة، مكيفة بالكامل، قريبة من الأسواق والمطاعم.',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400',
    images: [],
    ownerName: 'شقق النخيل',
    ownerPhone: '07809876544',
    promoted: false,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    userId: 'system',
    furnished: true,
  },
  {
    id: 'prop-6',
    title: 'محل تجاري في شارع الربيعي',
    price: 2500000,
    type: 'محل',
    purpose: 'إيجار',
    area: '60',
    beds: 0,
    baths: 1,
    location: 'بغداد - الربيعي',
    description: 'محل تجاري بواجهة زجاجية على الشارع الرئيسي، مساحة 60م، مناسب لجميع الأنشطة التجارية، كهرباء حكومية + مولدة.',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400',
    images: [],
    ownerName: 'صالح كريم',
    ownerPhone: '07901234568',
    promoted: false,
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    userId: 'system',
    furnished: false,
  },
];

export const sampleServiceProviders: ServiceProvider[] = [
  {
    id: 'srv-1',
    name: 'أحمد الكهربائي',
    specialty: 'كهرباء',
    rating: 4.9,
    jobs: 234,
    responseTime: '5 دقائق',
    verified: true,
    phone: '07701234570',
    location: 'بغداد - المنصور',
    description: 'كهربائي محترف، خبرة 15 سنة في الصيانة الكهربائية المنزلية والصناعية، تركيب لوحات كهربائية، صيانة مولدات.',
    image: '',
    autoReply: true,
    price: 'يبدأ من 15,000 د.ع',
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    userId: 'system',
  },
  {
    id: 'srv-2',
    name: 'محمد السباك',
    specialty: 'سباكة',
    rating: 4.8,
    jobs: 189,
    responseTime: '10 دقائق',
    verified: true,
    phone: '07801234570',
    location: 'بغداد - الكرادة',
    description: 'سباك متخصص في جميع أعمال السباكة والصحية، تركيب أطقم حمامات، صيانة سخانات، كشف تسربات المياه.',
    image: '',
    autoReply: true,
    price: 'يبدأ من 20,000 د.ع',
    createdAt: new Date(Date.now() - 86400000 * 45).toISOString(),
    userId: 'system',
  },
  {
    id: 'srv-3',
    name: 'علي الدهان',
    specialty: 'دهان',
    rating: 4.7,
    jobs: 156,
    responseTime: '15 دقيقة',
    verified: false,
    phone: '07711234570',
    location: 'بغداد - زيونة',
    description: 'دهان محترف، دهانات داخلية وخارجية، ديكورات جبس، ورق جدران، خبرة 10 سنوات.',
    image: '',
    autoReply: false,
    price: 'يبدأ من 25,000 د.ع',
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    userId: 'system',
  },
  {
    id: 'srv-4',
    name: 'حسن الميكانيكي',
    specialty: 'ميكانيك',
    rating: 4.9,
    jobs: 312,
    responseTime: '3 دقائق',
    verified: true,
    phone: '07501234570',
    location: 'بغداد - البياع',
    description: 'ميكانيكي سيارات متخصص، صيانة محركات بنزين وديزل، فحص كمبيوتر، تصليح جيرات أوتوماتيك.',
    image: '',
    autoReply: true,
    price: 'يبدأ من 10,000 د.ع',
    createdAt: new Date(Date.now() - 86400000 * 60).toISOString(),
    userId: 'system',
  },
  {
    id: 'srv-5',
    name: 'ورشة النجم للنجارة',
    specialty: 'نجارة',
    rating: 4.6,
    jobs: 98,
    responseTime: '20 دقيقة',
    verified: true,
    phone: '07901234570',
    location: 'أربيل - عينكاوا',
    description: 'ورشة نجارة متكاملة، تصنيع أثاث منزلي ومكتبي حسب الطلب، أبواب وشبابيك، مطابخ مودرن.',
    image: '',
    autoReply: false,
    price: 'حسب المشروع',
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    userId: 'system',
  },
  {
    id: 'srv-6',
    name: 'خدمات التكييف المركزي',
    specialty: 'تكييف',
    rating: 4.8,
    jobs: 278,
    responseTime: '8 دقائق',
    verified: true,
    phone: '07801234571',
    location: 'بغداد - المنصور',
    description: 'تركيب وصيانة أنظمة التكييف المركزي والسبلت، تعبئة غاز، تنظيف فلاتر، ضمان على الصيانة.',
    image: '',
    autoReply: true,
    price: 'يبدأ من 15,000 د.ع',
    createdAt: new Date(Date.now() - 86400000 * 25).toISOString(),
    userId: 'system',
  },
  {
    id: 'srv-7',
    name: 'فريق التنظيف المحترف',
    specialty: 'تنظيف',
    rating: 4.5,
    jobs: 145,
    responseTime: '30 دقيقة',
    verified: false,
    phone: '07701234571',
    location: 'البصرة - العشار',
    description: 'خدمات تنظيف شاملة للمنازل والمكاتب، تنظيف سجاد وكنب، غسيل واجهات زجاجية.',
    image: '',
    autoReply: false,
    price: 'يبدأ من 30,000 د.ع',
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    userId: 'system',
  },
];
